id = "ry"
name = "ry"
version = "0.1.1"
schema_version = 1
authors = ["Felix Andreas"]
description = "An R language server and code formatter, written in Rust."
repository = "https://github.com/felix-andreas/ry"

[language_servers.ry]
name = "ry"
language = "R"
