[package]
name = "semantics"
edition = "2024"
version.workspace = true
publish = false

[lib]
path = "src/semantics.rs"

[dependencies]
rowan.workspace = true
rustc-hash.workspace = true
salsa.workspace = true
serde = { workspace = true, features = ["derive"] }
stacker.workspace = true
syntax = { path = "../syntax" }
